create or replace function is_platform_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from profiles where id = auth.uid() and role = 'platform_admin'); $$;
create or replace function is_studio_member(target_studio_id uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from studio_members where studio_id = target_studio_id and user_id = auth.uid()); $$;
create or replace function touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create or replace function log_lead_stage_change() returns trigger language plpgsql as $$ begin if old.current_stage is distinct from new.current_stage then insert into lead_stage_history (studio_id, lead_id, from_stage, to_stage, changed_by) values (new.studio_id, new.id, old.current_stage, new.current_stage, auth.uid()); end if; return new; end; $$;
create or replace function update_customer_after_appointment() returns trigger language plpgsql as $$ begin if new.customer_id is not null then update customers set next_visit_at = case when new.status in ('scheduled','confirmed') then new.start_time else next_visit_at end, last_visit_at = case when new.status = 'completed' then new.start_time else last_visit_at end, first_visit_at = case when new.status = 'completed' and first_visit_at is null then new.start_time else first_visit_at end, appointment_count = (select count(*) from appointments where customer_id = new.customer_id and status <> 'cancelled'), updated_at = now() where id = new.customer_id; end if; if new.status = 'completed' and (tg_op = 'INSERT' or old.status is distinct from new.status) then insert into tasks (studio_id, customer_id, appointment_id, title, description, due_at, type) values (new.studio_id, new.customer_id, new.id, 'Retorno de 7 dias', 'Conferir cicatrizacao, orientar cuidados e estimular relacionamento.', new.start_time + interval '7 days', 'return_7_days'); end if; return new; end; $$;
drop trigger if exists trg_leads_updated_at on leads;
create trigger trg_leads_updated_at before update on leads for each row execute function touch_updated_at();
drop trigger if exists trg_customers_updated_at on customers;
create trigger trg_customers_updated_at before update on customers for each row execute function touch_updated_at();
drop trigger if exists trg_appointments_updated_at on appointments;
create trigger trg_appointments_updated_at before update on appointments for each row execute function touch_updated_at();
drop trigger if exists trg_tasks_updated_at on tasks;
create trigger trg_tasks_updated_at before update on tasks for each row execute function touch_updated_at();
drop trigger if exists trg_lead_stage_history on leads;
create trigger trg_lead_stage_history after update of current_stage on leads for each row execute function log_lead_stage_change();
drop trigger if exists trg_appointments_customer_rollup on appointments;
create trigger trg_appointments_customer_rollup after insert or update on appointments for each row execute function update_customer_after_appointment();
create or replace function create_inactive_30_day_tasks() returns void language sql security definer set search_path = public as $$ insert into tasks (studio_id, customer_id, title, description, due_at, type) select c.studio_id, c.id, 'Cliente 30 dias sem vir', 'Criar contato de reativacao.', now(), 'inactive_30_days' from customers c where c.last_visit_at < now() - interval '30 days' and not exists (select 1 from appointments a where a.customer_id = c.id and a.start_time > c.last_visit_at and a.status in ('scheduled','confirmed','completed')) and not exists (select 1 from tasks t where t.customer_id = c.id and t.type = 'inactive_30_days' and t.status <> 'cancelled'); $$;
create or replace function create_birthday_month_tasks() returns void language sql security definer set search_path = public as $$ insert into tasks (studio_id, customer_id, title, description, due_at, type) select c.studio_id, c.id, 'Aniversariante do mes', 'Registrar acao de relacionamento.', date_trunc('month', now()) + interval '1 month' - interval '1 day', 'birthday_month' from customers c where extract(month from c.birth_date) = extract(month from now()) and not exists (select 1 from tasks t where t.customer_id = c.id and t.type = 'birthday_month' and date_trunc('month', t.created_at) = date_trunc('month', now())); $$;
alter table studios enable row level security;
alter table profiles enable row level security;
alter table studio_members enable row level security;
alter table crm_stages enable row level security;
alter table customers enable row level security;
alter table leads enable row level security;
alter table lead_stage_history enable row level security;
alter table inbound_messages enable row level security;
alter table appointments enable row level security;
alter table tasks enable row level security;
alter table notes enable row level security;
alter table checklist_templates enable row level security;
alter table checklist_items enable row level security;
alter table studio_checklist_progress enable row level security;
alter table execution_scores enable row level security;
alter table agency_interest enable row level security;
drop policy if exists "profiles self or platform admin" on profiles;
create policy "profiles self or platform admin" on profiles for all using (id = auth.uid() or is_platform_admin()) with check (id = auth.uid() or is_platform_admin());
drop policy if exists "studios visible to members" on studios;
create policy "studios visible to members" on studios for select using (is_platform_admin() or is_studio_member(id));
drop policy if exists "studios manageable by platform admin" on studios;
create policy "studios manageable by platform admin" on studios for all using (is_platform_admin()) with check (is_platform_admin());
drop policy if exists "members visible by studio" on studio_members;
create policy "members visible by studio" on studio_members for select using (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "crm stages readable" on crm_stages;
create policy "crm stages readable" on crm_stages for select using (true);
drop policy if exists "checklist templates readable" on checklist_templates;
create policy "checklist templates readable" on checklist_templates for select using (true);
drop policy if exists "checklist templates admin write" on checklist_templates;
create policy "checklist templates admin write" on checklist_templates for all using (is_platform_admin()) with check (is_platform_admin());
drop policy if exists "customers tenant access" on customers;
create policy "customers tenant access" on customers for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "leads tenant access" on leads;
create policy "leads tenant access" on leads for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "lead history tenant access" on lead_stage_history;
create policy "lead history tenant access" on lead_stage_history for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "inbound messages tenant access" on inbound_messages;
create policy "inbound messages tenant access" on inbound_messages for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "appointments tenant access" on appointments;
create policy "appointments tenant access" on appointments for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "tasks tenant access" on tasks;
create policy "tasks tenant access" on tasks for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "notes tenant access" on notes;
create policy "notes tenant access" on notes for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "checklist items tenant access" on checklist_items;
create policy "checklist items tenant access" on checklist_items for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "checklist progress tenant access" on studio_checklist_progress;
create policy "checklist progress tenant access" on studio_checklist_progress for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "execution scores tenant access" on execution_scores;
create policy "execution scores tenant access" on execution_scores for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
drop policy if exists "agency interest tenant access" on agency_interest;
create policy "agency interest tenant access" on agency_interest for all using (is_platform_admin() or is_studio_member(studio_id)) with check (is_platform_admin() or is_studio_member(studio_id));
