insert into checklist_templates (month_number, suggested_week, title, description, category, points) values
  (1, 1, 'Ajustar bio do Instagram', 'Deixar proposta, cidade, especialidade e chamada para WhatsApp claros.', 'Instagram', 10),
  (1, 1, 'Organizar destaques', 'Separar informacoes essenciais para uma nova cliente entender o estudio.', 'Instagram', 10),
  (1, 1, 'Criar destaque de avaliacoes', 'Reunir provas sociais de clientes reais.', 'Instagram', 10),
  (1, 1, 'Criar destaque de cuidados', 'Publicar orientacoes basicas de cuidados pos-procedimento.', 'Atendimento', 10),
  (1, 2, 'Criar destaque de procedimentos', 'Mostrar os principais procedimentos com exemplos.', 'Instagram', 10),
  (1, 2, 'Criar destaque de ambiente', 'Mostrar higiene, estrutura e experiencia do studio.', 'Instagram', 10),
  (1, 2, 'Revisar link do WhatsApp', 'Garantir mensagem inicial e direcionamento corretos.', 'Atendimento', 5),
  (1, 2, 'Publicar prova social', 'Publicar depoimento, antes/depois permitido ou feedback.', 'Conteudo', 10),
  (1, 3, 'Publicar bastidores do studio', 'Mostrar processo, preparo e rotina profissional.', 'Conteudo', 10),
  (1, 3, 'Publicar conteudo educativo', 'Ensinar cuidado, escolha de joia ou duvidas comuns.', 'Conteudo', 10),
  (1, 3, 'Criar ou otimizar Google Meu Negocio', 'Conferir categoria, endereco, horarios, servicos e contato.', 'Google', 20),
  (1, 4, 'Subir fotos no Google', 'Adicionar fotos reais do ambiente e procedimentos permitidos.', 'Google', 10),
  (1, 4, 'Pedir primeiras avaliacoes', 'Criar rotina simples para solicitar reviews.', 'Google', 20),
  (1, 4, 'Criar modelo de resposta no WhatsApp', 'Padronizar primeiro atendimento sem perder tom humano.', 'Atendimento', 10),
  (2, 1, 'Publicar 3 conteudos por semana', 'Manter frequencia minima de conteudo local.', 'Conteudo', 20),
  (2, 1, 'Postar stories de bastidores', 'Gerar familiaridade e confianca na rotina.', 'Conteudo', 10),
  (2, 1, 'Pedir avaliacoes semanalmente', 'Manter entrada recorrente de reviews.', 'Google', 20),
  (2, 2, 'Atualizar fotos do Google', 'Adicionar fotos novas para fortalecer presenca local.', 'Google', 10),
  (2, 2, 'Analisar termos de busca local', 'Registrar como clientes procuram o servico na cidade.', 'Google', 10),
  (2, 2, 'Criar campanha sazonal simples', 'Planejar oferta conceitual ou tema de mes sem gestao de midia.', 'Trafego', 10),
  (2, 3, 'Criar lista de ideias de criativos', 'Separar angulos, fotos e provas sociais para futura agencia.', 'Trafego', 10),
  (2, 3, 'Revisar atendimento recebido', 'Avaliar clareza, tempo e objecoes nas conversas.', 'Atendimento', 10),
  (2, 3, 'Medir quantidade de conversas', 'Registrar volume de leads recebidos no periodo.', 'CRM', 10),
  (2, 4, 'Medir quantidade de agendamentos', 'Comparar conversas e agendamentos.', 'Conversao', 10),
  (2, 4, 'Criar rotina de follow-up manual', 'Definir quando Follow-up 1 e 2 acontecem.', 'CRM', 20),
  (3, 1, 'Medir leads recebidos', 'Consolidar entradas por canal.', 'CRM', 10),
  (3, 1, 'Medir clientes agendadas', 'Comparar volume de agendamentos por origem.', 'Conversao', 10),
  (3, 1, 'Medir taxa de fechamento', 'Calcular conversao de lead para cliente.', 'Conversao', 20),
  (3, 2, 'Revisar principais objecoes', 'Mapear duvidas e travas recorrentes.', 'Atendimento', 10),
  (3, 2, 'Revisar tempo medio de resposta', 'Avaliar velocidade do atendimento.', 'Atendimento', 10),
  (3, 2, 'Criar fluxo de recuperacao', 'Definir abordagem manual para leads frios.', 'CRM', 20),
  (3, 3, 'Criar campanha de retorno para clientes antigas', 'Planejar retomada de clientes inativas.', 'Conversao', 10),
  (3, 3, 'Organizar melhores criativos', 'Selecionar posts, fotos e provas sociais fortes.', 'Trafego', 10),
  (3, 3, 'Revisar Google Meu Negocio', 'Conferir fotos, reviews e informacoes.', 'Google', 10),
  (3, 4, 'Revisar Instagram', 'Conferir bio, destaques, conteudo e provas sociais.', 'Instagram', 10),
  (3, 4, 'Criar plano de aquisicao', 'Definir canais, rotina e hipotese de campanha conceitual.', 'Trafego', 20),
  (3, 4, 'Avaliar prontidao para trafego pago com agencia', 'Registrar se a base esta pronta para escalar profissionalmente.', 'Trafego', 20);
